### ISSUE TITLE
How you get 39.25% mAp on detectron2 with resnet50?

### ISSUE THREAD

**Issue by hanjianhua44** [zhanghang1989/ResNeSt#20]
Using Detectron2 can get 37.9% mAp on COCO, I tried to use syncBN on backbone, but only get 37.0% mAp, perhaps because it uses MSRA pretrained model. 

I haven't try use the sync-bn on FPN and detection head(with 4conv 1fc).

I wonder how you get 39.25 mAp on Detetron2, can you show me your settings?

**Comment by chongruo** [comment]
Here is the config.yaml

```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    STRIDE_IN_1X1: True
    DEPTH: 50
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1333
TEST:
  PRECISE_BN:
    ENABLED: True
```
