### ISSUE TITLE
image input format mismatch

### ISSUE THREAD

**Issue by yestinl** [zhanghang1989/ResNeSt#61]
When I use detectron2-ResNeSt, I found that the image input format is "RGB" in the *.yaml file, while the way read image  using "BGR" mode in the demo.py. So does this inconsistency affect the results?

Code in demo.py
```
if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)
    args = get_parser().parse_args()
    setup_logger(name="fvcore")
    logger = setup_logger()
    logger.info("Arguments: " + str(args))

    cfg = setup_cfg(args)

    demo = VisualizationDemo(cfg)

    if args.input:
        if len(args.input) == 1:
            args.input = glob.glob(os.path.expanduser(args.input[0]))
            assert args.input, "The input path(s) was not found"
        for path in tqdm.tqdm(args.input, disable=not args.output):
            # use PIL, to be consistent with evaluation
            img = read_image(path, format="BGR")
```
Setting in faster_cascade_rcnn_ResNeSt_200_FPN_syncbn_range-scale_1x.yaml
```
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1333
  FORMAT: "RGB"
```
